### ISSUE TITLE
Config for Pebble Cloud and emulator

### ISSUE THREAD

**Issue by clach04** [openhab/openhab.pebble#10]
AppConfig doesn't work under the emulator.

Not sure if this is related to issue #1 or not.

I have a fix, but I can't locate the code to make a pull request against. Code is at https://github.com/clach04/clach04.github.io/commit/ad9792c4a595d3655239aec600b106cd990decfc

**Comment by llamahunter** [comment]
It's under the gh-pages branch of the openhab.pebble repo.  https://github.com/openhab/openhab.pebble/tree/gh-pages

**Comment by clach04** [comment]
PR #11
