### ISSUE TITLE
Change app name from "OpenHAB for Pebble" to "openHAB"

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab.pebble#22]
I noticed that the openHAB app stands out of the Pebble app store a bit, because it is the only one nowadays using the "for Pebble" suffix. I think it should therefore be renamed to simply "openHAB".

**Comment by llamahunter** [comment]
Sure... at the time I named it, I was trying to draw some distinction between my project and 'openHAB', but now that it's all in the same github organization, probably doesn't matter.

**Comment by llamahunter** [comment]
closed by #27, but will need a push to pebble store to make it complete.

**Comment by kaikreuzer** [comment]
You might also want to update [some further references](https://github.com/openhab/openhab.pebble/search?utf8=%E2%9C%93&q=OpenHAB+for+Pebble&type=Code) (also make sure to spell openHAB with a small "o").

Well, thinking about it, the "for Pebble" addition makes sense on those places, so all there is left to change are the capital Os.

When I am in the app settings on my phone, though, it still shows me "OpenHAB for Peb..." at the very top - do you have any clue, where this string comes from?

**Comment by llamahunter** [comment]
Ah... have to change the gh-pages to fix the settings.

**Comment by llamahunter** [comment]
fixed

**Comment by kaikreuzer** [comment]
Thanks again :-)
