### ISSUE TITLE
Pebble config URL mismatch

### ISSUE THREAD

**Issue by abeulich** [openhab/openhab.pebble#44]
The settings page for the Pebble openhab app returns a 404 error since the beginning of January 2018. It looks like there is a typo in the URL and it doesn't match with the app anymore. Please see here: https://community.openhab.org/t/settings-returns-a-404-error/38106 .

Can this be fixed please? 

Best regards, Alex

**Comment by ghys** [comment]
Thanks! This was already reported in #43 - we'll fix this.

**Comment by abeulich** [comment]
Thanks. I didn't find it in the open issues. ;) 
Thanks for taking care of it. Looking forward to the fix.

Cheers, Alex

**Comment by kaikreuzer** [comment]
This was due to a repo renaming - I just reverted it, so I hope the issue is fixed.

**Comment by abeulich** [comment]
I can confirm the settings page works again and so does the openhab pebble app on the watch. 

Thanks for fixing it!

**Comment by kaikreuzer** [comment]
Please note that I just published version 1.8, which now again refers to openhab-pebble as a repo - so please make sure to update your watch to this release!

**Comment by mrwhale** [comment]
re-opening this one!

Just started using my pebble again and the config page does not work - http://openhab.github.io/openhab-pebble/ redirects to https://www.openhab.org/openhab-pebble/ which gives a 404

**Comment by kaikreuzer** [comment]
Thanks for noticing, this is due to our new website indeed - @ghys could you please make the `openhab-pebble` path available on the new webserver as well? Thanks!

**Comment by ghys** [comment]
Should work again - please test and reopen if necessary, thanks!
