### ISSUE TITLE
Please Link Pebble Dev Account to a Rebble Account

### ISSUE THREAD

**Issue by CameronDevine** [openhab/openhab.pebble#46]
To allow the continued use and updates of One Bus Away on Pebble Devices, please make a Rebble account and link the Pebble Developer account for this Pebble app.

You can read more about Rebble here,
http://rebble.io/2018/06/13/get-ready-to-rebble.html

**Comment by kaikreuzer** [comment]
Thanks for the hint - I already read this blog post earlier this week and created a linked Rebble account; I hope we are all set for the switch.
